Loading data for cleanup of RAPID3:
resolving scores for rapid3:
(152, 22)
(130, 22)
resolve_fractional_score.py:121: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pro_scores['score_updated_num'][row[0]] = np.nan
Statistics for instrument:  rapid3
---------------------------------------------
Number of unique patients:  106
  
Number of unique practice:  14
---------------------------------------------
Date range:
2015-01-26
2018-06-13
---------------------------------------------
Score range:
0.0
24.3
---------------------------------------------
Number of assessments:  130
